elm install elm/http
elm install elm/json
elm install elm/browser
elm install elm/core
elm install elm/http
elm install elm/time
elm install elm/url
elm install avh4/elm-color
elm install rtfeldman/elm-hex
elm install elm/file
